### ISSUE TITLE
Feature request: automatic bitrate inspection

### ISSUE THREAD

**Issue by nrmmota** [KwikFlixTV/kwik-udp-send#2]
Automatic bitrate would be a big plus. I guess the worst case scenario would be VBR files. This would be my goto swiss knife for multicast streams in that case.

**Comment by mesouug** [comment]
Good day.

Unfortunately implementing this feature not possible due to simplicity of code base. In order to determine bitrate One need to parse ts stream which is rather complicated. This tool wasn't designed for such task. Maybe future tools can do that. Right now not possible.

Thanks,
Mikhail.
